version: '3'

services:

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - alpine-net
  
  apache:
    container_name: apache
    hostname: apache
    build: 
      context: apache
      dockerfile: Dockerfile    
    ports:
      - 8001:80
    networks:
      - alpine-net

  gateway-proxy:
    container_name: gateway-proxy
    build: gateway-proxy
    ports:
      - 80:80
    networks:
      - alpine-net
    depends_on:
      - nginx
      - apache

  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306

networks:
  alpine-net:
    driver: bridge
volumes:
  db-data:
secrets:
  db-password:
    file: db-password.txt