version: '3'

services:

  nginx:
    container_name: gateway
    hostname: gateway
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - alpine-net
  
  apache:
    container_name: apache
    hostname: apache
    build: 
      context: apache
      dockerfile: Dockerfile    
    ports:
      - 8001:80
    networks:
      - alpine-net

  gateway-proxy:
    container_name: gateway-proxy
    build: gateway-proxy
    ports:
      - 80:80
    networks:
      - alpine-net
    depends_on:
      - nginx
      - apache

networks:
  alpine-net:
    driver: bridge